swagger: '2.0'
info:
  description: 'The API provides an option to get all advertisers <br> versionHistory <br> -------------- <br> 2020-Apr-15 Marina Yurovsky - Version - 1.0.0. - Initial version.'
  version: '1.0'
  title: Advertiser List External API POST
  contact:
    name: API team
    email: apiteam@operative.com
  license:
    name: Copyright 2020 Operative
host: 'dev-mdm-service01.cloud.operative.com:9191'
basePath: /
tags:
  - name: Advertiser
    description: Advertiser Controller
consumes:
  - application/json
produces:
  - application/json
paths:
  '/v1/{apiKey}/internal/advertiser':
    post:
      tags:
        - Advertiser
      summary: Returns paginated list containing AOS Advertisers
      operationId: listAdvertiserUsingPOST
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: size
          in: query
          description: Number of Advertisers returned per page
          type: integer
          format: int32
          minimum: 0
          exclusiveMinimum: true
          maximum: 1000
          exclusiveMaximum: false
          multipleOf: 100
          default: 100
        - name: page
          in: query
          description: Page number
          type: integer
          default: 0
        - name: status
          in: query
          description: Advertiser Status
          required: false
          type: boolean
          default: 'true'
        - name: apiKey
          in: path
          description: apiKey
          required: true
          type: string
        - type: string
          in: query
          name: Last Modified DateTime
          description: Return Advertisers that were added or changed since the date selected
        - name: external Source System ID
          in: query
          description: External source system identifier of an Advertiser
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Page«Advertiser»'
        '400':
          description: 'Bad Request. Please verify your request '
          schema:
            type: object
            properties: {}
        '403':
          description: Forbidden. Please verify access permissions for the AOS APIs.
          schema:
            type: object
            properties: {}
        '500':
          description: An unexpected error occured.
          schema:
            type: object
            properties: {}
      deprecated: false
      description: A paginated list of Advertisers with limited attributes. It can be used for mapping of the AOS IDs to IDs in an external system.
definitions:
  Advertiser:
    type: object
    title: Advertiser
    properties:
      id:
        type: string
        description: AOS identifier of an Advertiser
      lastModifiedDate:
        type: string
        format: date-time
        example: '2016-06-10T12:36:58.014Z'
        description: 'Last date time of the modification '
      mdmId:
        type: string
        description: External source system Identifier
      name:
        type: string
        description: Advertiser name
    description: Data object that contains attirbutes of an Advertiser
    x-examples:
      advertiser:
        id: string
        lastModifiedDate: '2016-06-10T12:36:58.014Z'
        mdmId: string
        name: string
  Sort:
    type: object
    properties:
      empty:
        type: boolean
      sorted:
        type: boolean
      unsorted:
        type: boolean
    title: Sort
    description: Data object that contains sort paramters
  Page«Advertiser»:
    type: object
    title: Page«Advertiser»
    x-examples:
      example-1: {}
    description: Data object that contains attributes of the Advertiser page returned by the API call
    properties:
      content:
        type: array
        description: Advertiser records returned by the API call
        items:
          $ref: '#/definitions/Advertiser'
      size:
        type: integer
        format: int32
        description: Number of Advertisers returned per page
      sort:
        $ref: '#/definitions/Sort'
      totalElements:
        type: integer
        format: int64
        description: Total number of the Advertiser records returned
      totalPages:
        type: integer
        format: int32
        description: Total number of returned pages
schemes:
  - https
securityDefinitions: {}
