swagger: '2.0'
info:
  description: "CRM Service API acts as a bridge between Planner and any external system . It manages Opportunities and Lines. <br> versionHistory <br> -------------- <br> 2020-Apr-16 Marina Yurovsky - Version - 1.0.0. - Initial version.'"
  version: '1.0'
  title: CRM Service API
  license:
    name: Copyright 2020 Operative
  contact:
    name: API team
    email: apiteam@operative.com
  termsOfService: 'http://www.operative.com'
host: aos-dev-gw.operativeone.com
basePath: /crm
tags:
  - name: Opportunity API
    description: Opportunity Create And Update External Controller
consumes:
  - application/json
produces:
  - application/json
paths:
  '/v1/{apiKey}/opportunities':
    post:
      tags:
        - Opportunity API
      summary: Creates a new Opportunity
      description: Creates a new Opportunity in AOS
      operationId: createOpportunityUsingPOST
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: apiKey
          in: path
          description: apiKey
          required: true
          type: string
        - in: body
          name: opportunityDTO
          description: Opportunity and Opportunity Lines Data Object
          required: true
          schema:
            $ref: '#/definitions/OpportunityDTO'
      responses:
        '200':
          description: Successful Operation
          schema:
            type: string
        '201':
          description: Created
        '400':
          description: Invalid Request Body
          schema:
            type: string
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: FORBIDDEN
          schema:
            type: string
        '404':
          description: Not found
          schema:
            type: string
        '500':
          description: INTERNAL_SERVER_ERROR
          schema:
            type: string
      deprecated: false
    put:
      tags:
        - Opportunity API
      summary: Updates a new Opportunity
      description: Updates a new Opportunity
      operationId: updateOpportunityUsingPUT
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: apiKey
          in: path
          description: apiKey
          required: true
          type: string
        - in: body
          name: opportunityDTO
          description: Opportunity
          required: true
          schema:
            $ref: '#/definitions/OpportunityDTO'
      responses:
        '200':
          description: Successful Operation
          schema:
            type: string
        '201':
          description: Created
        '400':
          description: Invalid Request Body
          schema:
            type: string
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: FORBIDDEN
          schema:
            type: string
        '404':
          description: Not found
          schema:
            type: string
        '500':
          description: INTERNAL_SERVER_ERROR
          schema:
            type: string
      deprecated: false
definitions:
  OpportunityDTO:
    type: object
    title: OpportunityDTO
    description: Data obect that contains Opportunity and Opportunity LInes.
    properties:
      accountExecutive:
        type: string
      advertiserId:
        type: string
        description: AOS ID of an Advertiser
      agencyId:
        type: string
        description: AOS ID of an Agency
      amount:
        type: number
        format: double
        description: Projected Amount
      attributes:
        type: object
        additionalProperties:
          type: string
        description: 'Additional Opportunity attributes, plan class, deal year, marketplace, etc.'
        properties:
          planClassID:
            type: string
            description: AOS ID of the Plan class
      flightEndDate:
        type: string
        description: Opportunity Flight End Date
      flightStartDate:
        type: string
        description: Opportunity Flight Start Date
      lineItems:
        type: array
        description: Array that contains a list of the Opportunity Lines
        items:
          $ref: '#/definitions/OpportunityLineItemDTO'
      name:
        type: string
        description: Opportunity name
      planId:
        type: string
        description: AOS Plan ID
      platform:
        type: string
      externalSystemId:
        type: string
        description: External ID of the Opportunity
    required:
      - accountExecutive
      - advertiserId
      - agencyId
      - flightEndDate
      - flightStartDate
  OpportunityLineItemDTO:
    type: object
    properties:
      attributes:
        type: object
        additionalProperties:
          type: string
      lineItemId:
        type: string
    title: OpportunityLineItemDTO
schemes:
  - https
