swagger: '2.0'
info:
  description: 'The API provides an opetion to get Plan Lines for a given Plan ID. <br> versionHistory <br> -------------- <br> 20202-Apr-11 Marina Yurovsky - Version - 1.0.0. - Initial version.'
  version: '1.0'
  title: Plan Workspace Weekly External API GET
  contact:
    name: API team
    email: apiteam@operative.com
  license:
    name: Copyright 2020 Operative
host: tvs-dev-gw.operativeone.com
basePath: /external_planner
tags:
  - name: plan-header-workspace_external-controller
    description: Plan Header and Workspalce External Controller
consumes:
  - application/json
produces:
  - application/json
paths:
  '/v1/{apiKey}/plan/{planId}/workspace/summary/week':
    post:
      tags:
        - plan-header-workspace_external-controller
      summary: Get weekly summary per demo
      description: Get line totals per week per demo
      operationId: getPeriodSummarybyDemo
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: apiKey
          in: path
          description: apiKey
          required: true
          type: string
        - name: planId
          in: path
          description: planId
          required: true
          type: string
        - in: body
          name: periodTotalRequest
          description: periodTotalRequest
          required: false
          schema:
            $ref: '#/definitions/PeriodTotalRequest'
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
              additionalProperties:
                $ref: '#/definitions/PlanTotalDTO'
      deprecated: false
    parameters:
      - type: string
        name: apiKey
        in: path
        required: true
      - type: string
        name: planId
        in: path
        required: true
definitions:
  Channel:
    type: object
    title: Channel
    x-examples:
      channel:
        id: nEZkdsMzSmKkf1w8fBOpUw
        name: Best TV
        code: BTV
    description: Data object that contains attirbutes of the Channel
    properties:
      id:
        type: string
        description: AOS Identifier of the Channels - Stations MRD
        example: '5e2540844d9c00600d5a000a, C4gyuWfTQZ-BtJLmLZE_rA'
      code:
        type: string
        description: Abbriviated name of the channel - call letters
      name:
        type: string
        description: Channel name
  Period:
    type: object
    title: Period
    x-examples:
      period:
        id: '18675'
        name: 4Q20
    description: Data object that contains attributes of a calendar period
    properties:
      id:
        type: string
        description: AOS ID of the period for the week on the line -  Calendar MRD.
      name:
        type: string
        description: Name of the calendar period
  DemoValues:
    type: object
    title: DemoValues
    description: Data object that contains information about various mesures available for the Plan Demo.
    properties:
      cpm:
        type: number
        format: double
        description: Cost per thousand impressions
      factor:
        type: number
        format: double
      grps:
        type: number
        format: double
        description: Gross rating points
      imps:
        type: number
        format: double
        description: Estimated Impressions
      index:
        type: number
        format: double
      nationalUe:
        type: number
        format: double
        description: Estimated universe of all people subscribed to the channel
      vpvh:
        type: number
        format: double
        description: Viewers per viewing household
      rcCpm:
        type: number
        description: Cost per thousand impressions calculated based on ratecard rate and estimated impressions.
      cpp:
        type: number
        description: Cost per rating point
      guaranteedImps:
        type: number
        description: Based on the line class. If guaranteed then guaranteed impressions
  UnitRates:
    type: object
    title: UnitRates
    description: Data object that contains information about units and rates
    properties:
      rate:
        type: number
        format: double
        description: Total Rate of a all units in the week
      rcRate:
        type: number
        format: double
        description: Ratecard rate of a units in the week
      units:
        type: integer
        format: int64
        description: Number of units in a week for a Plan Line
  PeriodTotalRequest:
    type: object
    title: PeriodTotalRequest
    properties:
      lineIds:
        type: array
        items:
          type: string
      week:
        type: string
  PlanTotalDTO:
    type: object
    title: PlanTotalDTO
    description: ''
    properties:
      channelId:
        $ref: '#/definitions/Channel'
      demoValues:
        type: object
        additionalProperties:
          $ref: '#/definitions/DemoValues'
      lineId:
        type: string
      planId:
        type: string
      unitRates:
        $ref: '#/definitions/UnitRates'
      week:
        type: string
      daypart:
        $ref: '#/definitions/daypart'
      period:
        $ref: '#/definitions/Period'
  daypart:
    type: object
    title: daypart
    description: Data object that contains attributes of the daypart
    properties:
      id:
        type: string
        description: AOS ID of the Daypart
      name:
        type: string
        description: Daypart Name
schemes:
  - https
