paths:
  '/v1/{apiKey}/plan':
    post:
      tags:
        - plan-list_external-controller
      summary: Get All Plan sorted by field
      description: Get all Plans sorted by field
      operationId: getPlanPageSortedByField
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: apiKey
          in: path
          description: apiKey
          required: true
          type: string
        - name: fieldName
          in: query
          description: fieldName
          required: true
          type: string
        - in: body
          name: filter
          description: Filter Proposal
          required: false
          schema:
            $ref: '#/definitions/PlanListFilter'
        - name: pageNo
          in: query
          description: pageNo
          required: true
          type: string
        - name: pageSize
          in: query
          description: pageSize
          required: true
          type: string
        - name: sortOrder
          in: query
          description: sortOrder
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Plan'
      deprecated: false
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: plan-list_external-controller
    description: Plan List External Controller
basePath: /external_planner
host: tvs-dev-gw.operativeone.com
info:
  description: 'The API provides a paginated list of all plans based on the filters. <br> versionHistory <br> -------------- <br> 2020-Apr-28 Marina Yurovsky - Version - 1.0.0. - Initial version.'
  version: '1.0'
  title: List all Plans External API POST
  contact:
    name: API team
    email: apiteam@operative.com
  license:
    name: Copyright 2020 Operative
swagger: '2.0'
definitions:
  Plan:
    type: object
    title: Plan
    properties:
      createdBy:
        type: string
      createdDate:
        type: string
        format: date-time
      Header:
        $ref: '#/definitions/PlanHeader'
      id:
        type: string
      lastModifiedBy:
        type: string
      lastModifiedDate:
        type: string
        format: date-time
      planId:
        type: integer
        format: int64
      revision:
        type: number
    description: Data object that contains atrributes of the Plan
  PlanHeader:
    type: object
    title: PlanHeader
    properties:
      AccountExecutives:
        type: array
        items:
          $ref: '#/definitions/AccountExecutives'
      Advertisers:
        type: array
        items:
          $ref: '#/definitions/Advertiser'
      Agencies:
        type: array
        items:
          $ref: '#/definitions/Agencies'
      Calendar:
        $ref: '#/definitions/Calendar'
      Channels:
        type: array
        items:
          $ref: '#/definitions/Channels'
      CustomFields:
        items:
          $ref: '#/definitions/CustomFields'
        type: array
      DealYear:
        items:
          $ref: '#/definitions/DealYear'
        type: array
      Demos:
        type: array
        items:
          $ref: '#/definitions/Demos'
      dueDate:
        type: string
        example: 'yyyy-MM-dd,hh:mm a'
      endDate:
        type: string
        format: date
        example: '2020-04-17'
      equivalised:
        type: boolean
      fluidity:
        type: boolean
      guaranteed:
        type: boolean
      Hiatus:
        type: array
        items:
          $ref: '#/definitions/Hiatus'
      OrderType:
        $ref: '#/definitions/OrderType'
      PlanClass:
        $ref: '#/definitions/PlanClass'
      planName:
        type: string
      planNotes:
        type: string
      PlanStatus:
        $ref: '#/definitions/PlanStatus'
      platform:
        type: string
        enum:
          - LINEAR
          - DIGITAL
          - CONVERGED
      Ratecard:
        type: array
        items:
          $ref: '#/definitions/Ratecard'
      RatingStream:
        $ref: '#/definitions/RatingStream'
      startDate:
        type: string
        format: date
        example: '2020-09-30'
      ExternalSourceSystems:
        $ref: '#/definitions/ExternalSourceSystems'
      PrimaryVersion:
        type: array
        items:
          $ref: '#/definitions/PrimaryVersion'
      StartPeriod:
        $ref: '#/definitions/Period'
      Marketplace:
        $ref: '#/definitions/Marketplace'
      EndPeriod:
        $ref: '#/definitions/Period'
    x-examples:
      example-1: {}
    description: Data object that contains attributes of the Plan header
  Ratecard:
    type: object
    title: Ratecard
    x-examples:
      ratecard:
        id: 5e8c69dd754aba7146e2a6de
        name: 'IP Test RC Deportes Apr 07 2020 11:32:42 AM Apr 07 2020 11:54:05 AM'
        channel:
          id: Nou_azxVQs6uopaWpzH7Hg
          name: Deportes
          code: Deportes
          isPrimary: false
          ratingSource: null
          ratingStream: null
          hhPostBuyId: null
          demoPostBuyId: null
          division: null
          subDivision: null
          primary: false
        asOfDate: '2020-04-15'
        revision: 1
    properties:
      asOfDate:
        type: string
        format: date
      channelId:
        type: string
      id:
        type: string
      revision:
        type: number
      name:
        type: string
  PlanStatus:
    type: object
    title: PlanStatus
    x-examples:
      plan status:
        approvers:
          - id: null
            name: John Doe
            userId: xxx@domain.com
        statusId: Working
        statusName: Working
    properties:
      statusId:
        type: string
      statusName:
        type: string
  Division:
    type: object
    title: Division
    x-examples:
      division:
        id: xzxDdDspRRSafgUY8zs7bw
        name: Entertainment
    properties:
      id:
        type: string
        description: AOS ID of the Division
      name:
        type: string
    required:
      - id
  Calendar:
    type: object
    title: Calendar
    properties:
      id:
        type: string
        description: AOS ID of the Calendar
      name:
        type: string
      startDate:
        type: string
      endDate:
        type: string
      calendarBase:
        type: string
  Agencies:
    type: object
    title: Agencies
    x-examples:
      Agency:
        id: 5ddf63114d9c003405f35df3
        name: "America's Health Insurance Plans"
        commission: null
        rolesData:
          - BY
        roles:
          - Buying
        contact: null
        address: null
        effectiveDate: '2020-04-17'
    description: Data object that contains attribute of the agencies assigned to the plan.
    properties:
      address:
        type: string
      commission:
        type: string
        description: Not required. If empty then default from the MDM Agency
      startDate:
        type: string
        format: date
      id:
        type: string
        description: AOS ID for the Agency MDM
      roles:
        type: array
        description: 'Roles assigned to the agencies. Options are: Buying, Paying and Billing'
        items:
          type: string
      endDate:
        type: string
      Contact:
        $ref: '#/definitions/Contact'
  Channels:
    type: object
    title: Channels
    x-examples:
      channel:
        id: nEZkdsMzSmKkf1w8fBOpUw
        name: Best TV
        code: BTV
        isPrimary: true
        ratingStream: C3
        hhPostBuyId: null
        demoPostBuyId: null
    properties:
      id:
        type: string
        description: List of comma separated AOS Identifier of the Channels - Stations MRD
        example: '5e2540844d9c00600d5a000a, C4gyuWfTQZ-BtJLmLZE_rA'
      code:
        type: string
      name:
        type: string
      isPrimary:
        type: boolean
      hhPostBuyId:
        type: string
      hhPostBuyName:
        type: string
      demoPostBuyId:
        type: string
      demoPostBuyName:
        type: string
      Division:
        $ref: '#/definitions/Division'
      subDivision:
        $ref: '#/definitions/SubDivision'
  Demos:
    type: object
    title: Demos
    x-examples:
      demo:
        id: '11'
        name: M18-32
        isPrimary: true
        edi: true
        postby: true
    properties:
      id:
        type: string
        description: Comma separated list of AOS IDs for the Demographic. The first element in the list is an ID of the Primary Demo.
      name:
        type: string
      isPrimary:
        type: boolean
      edi:
        type: boolean
      postBuy:
        type: boolean
  AccountExecutives:
    type: object
    title: AccountExecutives
    x-examples:
      Account Exec:
        name: API User
        id: '2'
        isPrimary: true
        startDate: null
        endDate: null
        split: 100
        role: null
        title: ae
        teamId: ''
        teamName: ''
        effectiveDate: null
        primary: true
    description: Data object contains information about Account exectives assigned to the Plan
    properties:
      endDate:
        type: string
        format: date
        description: Not required. If empty default the Flight End date
      id:
        type: string
        description: if empty then API needs to assigned AOS User ID else TBD if email is ok for PITCH
      isPrimary:
        type: boolean
        description: true if Account Executive is Primary
      role:
        type: array
        description: 'Sales Position of the Account Executive. For example: ae, sales planner, sales assistant'
        items:
          type: string
      split:
        type: number
        description: 'Not required. If empty default to 100%'
      startDate:
        type: string
        format: date
        description: Not required If empty default to Flight Start Date
      team:
        $ref: '#/definitions/Team'
      name:
        type: string
        description: Account executive name
  Team:
    type: object
    title: Team
    description: Object that contains information about the team that is managing a Plan.
    properties:
      id:
        type: string
      name:
        type: string
  Advertiser:
    type: object
    title: Advertiser
    x-examples:
      advertiser:
        id: 5dee3bae4d9c000a905b43ef
        name: Zephyr Advertsers
        categoryId: 5e7a15d24d9c0017f51d26bd
        secCategoryId: 5e4e458f4d9c0028f7c3280f
        address: null
        brand:
          id: string
          name: Best brand
        contact:
          id: string
          name: Joe Smith
    description: Data Object that contains information for an Advertiser
    properties:
      id:
        type: string
        description: Advertiser Id
      name:
        type: string
        description: Advertiser name
      category:
        type: string
        description: Primary industry category for an Advertiser
      subCategory:
        type: string
        description: Secondary industry category
      address:
        type: string
      Brand:
        $ref: '#/definitions/Brand'
      Contact:
        $ref: '#/definitions/Contact'
  DealYear:
    type: object
    title: DealYear
    x-examples:
      deal year:
        id: pGEAriBjS_WjXyhOilJPTQ
        name: 2020 DY
        startDate: '2020-03-26'
        endDate: '2021-03-01'
    properties:
      id:
        type: string
      name:
        type: string
      startDate:
        type: string
      endDate:
        type: string
  Marketplace:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: Marketplace
  RatingStream:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: RatingStream
  CustomFields:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: CustomFields
  PlanClass:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: PlanClass
  Contact:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: Contact
  ExternalSourceSystems:
    type: object
    title: ExternalSourceSystems
    properties:
      extSourceID:
        type: string
        description: AOS ID of the External Sysem
      externalID:
        type: string
        description: 'Unique ID in the External system, like Opportunity ID'
    x-examples:
      example-1: {}
  SubDivision:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: SubDivision
  Hiatus:
    type: object
    properties:
      endDate:
        type: string
        format: date
      startDate:
        type: string
        format: date
    title: Hiatus
    x-examples:
      example-1: {}
  Period:
    type: object
    title: Period
    x-examples:
      period:
        id: 4Q20
        name: 4Q20
    description: Data object that contains attributes of a calendar period
    properties:
      id:
        type: string
        description: AOS ID from the Calendar MRD. If empty default to the period for the flight end date
      name:
        type: string
      startDate:
        type: string
      endDate:
        type: string
  OrderType:
    type: object
    properties:
      id:
        type: string
        description: AOS ID of the order type MRD
      name:
        type: string
    title: OrderType
    x-examples:
      order type:
        id: default
        name: default
  User:
    type: object
    title: User
    properties:
      id:
        type: string
        description: AOS ID of a user in UM
      name:
        type: string
        description: User Name
      userId:
        type: string
  PlanListFilter:
    type: object
    title: PlanListFilter
    description: Data object that contains all available filters for the Plan List API
    properties:
      AccountExecutives:
        type: array
        items:
          $ref: '#/definitions/User'
      Advertisers:
        type: array
        items:
          $ref: '#/definitions/Advertiser'
      Agencies:
        type: array
        items:
          $ref: '#/definitions/Agencies'
      Channels:
        type: array
        items:
          $ref: '#/definitions/Channels'
      DealYears:
        type: array
        items:
          $ref: '#/definitions/DealYear'
      Demos:
        type: array
        items:
          $ref: '#/definitions/Demos'
      flightDate:
        type: string
      flightEndDate:
        type: string
        example: MM/dd/yyyy
      flightStartDate:
        type: string
        example: MM/dd/yyyy
      lastModifiedDate:
        type: string
      MarketPlaces:
        type: array
        items:
          $ref: '#/definitions/Marketplace'
      PlanClasses:
        type: array
        items:
          $ref: '#/definitions/PlanClass'
      planId:
        type: integer
        format: int64
      planName:
        type: string
      PlanStatuses:
        type: array
        items:
          $ref: '#/definitions/PlanStatus'
      Teams:
        type: array
        items:
          $ref: '#/definitions/Team'
  Brand:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: Brand
  PrimaryVersion:
    type: object
    title: Primary Version
    description: Object that contains attributes of a Plan Version.
    x-examples:
      example-1: {}
    properties:
      createdBy:
        $ref: '#/definitions/User'
      createdDate:
        type: string
        format: date-time
        description: Date when the Plan version was created
      id:
        type: integer
        format: int64
      modifiedBy:
        $ref: '#/definitions/User'
      modifiedDate:
        type: string
        format: date-time
        description: Date when a Plan version was last modified
      name:
        type: string
        description: Plan Version name
      primary:
        type: boolean
        description: True if for primary version of the plan
      ExternalSourceSytems:
        $ref: '#/definitions/ExternalSourceSystems'
schemes:
  - https
