definitions:
  ExternalSourceSystems:
    type: object
    title: ExternalSourceSystems
    properties:
      extSourceID:
        type: string
        description: AOS ID of the External Sysem
      externalID:
        type: string
        description: 'Unique ID in the External system, like Opportunity ID'
  Hiatus:
    type: object
    properties:
      endDate:
        type: string
        format: date
        description: End date of the hiatus period in yyyy-MM-dd format
      startDate:
        type: string
        format: date
        description: Start date of the hiatus period in yyyy-MM-dd format
    title: Hiatus
    x-examples:
      Hiatus:
        startDate: '2021-09-27'
        endDate: '2021-10-03'
    description: Data obect that dates and/or date ranges when the advertiser does not want air the commercials.
    required:
      - id
  Advertisers:
    type: object
    title: Advertisers
    description: Data object that contains attributes of an Advertiser
    x-examples:
      advertiser:
        id: 5dee3bae4d9c000a905b43ef
        categoryId: 5e7a15d24d9c0017f51d26bd
        secCategoryId: 5e4e458f4d9c0028f7c3280f
    properties:
      id:
        type: string
        description: Advertiser Id
      categoryId:
        type: string
        description: AOS ID of the Primary industry category for an Advertiser
      secCatgoryId:
        type: string
        description: AOS ID of the secondary industry category for an Advertiser
      contactId:
        type: string
        description: AOS ID of the Primary Advertiser contact person. Not required
      brandId:
        type: string
        description: AOS ID of the default Brand for an Advertiser. Not required
      address:
        type: string
        description: Address of the Primary Advertiser contact. Not required
  AccountExecutives:
    type: object
    title: AccountExecutives
    x-examples:
      Joe Smith Primary AE:
        name: Joe Smith
        id: '40'
        isPrimary: true
        startDate: '2021-08-10'
        endDate: '2022-07-12'
        split: 100
        role: ae
        effectiveDate: '2021-08-10'
    description: 'Account Executives for the Plan. '
    properties:
      endDate:
        type: string
        default: If empty default the Flight End date
        description: Not required. If empty default the Flight End date
        format: date
        example: '2021-08-30'
      id:
        type: string
        description: if empty then API needs to assigned AOS User ID else TBD if email is ok for PITCH
      isPrimary:
        type: boolean
        description: Required
      role:
        type: string
        description: AOS ID of the Sales position in MRD
      split:
        type: number
        description: 'Not required. If empty default to 100%'
      startDate:
        type: string
        format: date
        description: Not required If empty default to Flight Start Date
    required:
      - id
  GenericResponse:
    type: object
    properties:
      errorMsg:
        type: array
        items:
          type: string
      httpStatusCode:
        type: string
        enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
      id:
        type: string
      response:
        type: object
      successMsg:
        type: string
    title: GenericResponse
  RateCards:
    type: object
    title: RateCards
    description: Data obect that Ratecard information.
    properties:
      asOfDate:
        type: string
        format: date
        description: Find all ratecards that were published to use in planning as of the date specified
      channelId:
        type: string
        description: AOS ID of the Channel - Station MRD. Must be one of the channels selected for the plan header
      id:
        type: string
        description: AOS ID  for the Ratecard in URC
      revision:
        type: number
        description: Ratecard revision.
  Demos:
    type: object
    title: Demos
    description: Data object the contains Demo attributes
    properties:
      id:
        type: string
        description: AOS ID of the Demographic MRD
      isPrimary:
        type: boolean
        description: True if the demo is primary for the Plan
    required:
      - id
      - isPrimary
  Channels:
    type: object
    title: Channels
    x-examples:
      Channel:
        id: C4gyuWfTQZ-BtJLmLZE_rA
        isPrimary: true
        hhPostBuyID: null
        demoPostBuyId: null
    description: Data object the contains Chhannel attributes
    properties:
      id:
        type: string
        description: AOS Identifier of the Channels - Stations MRD
      isPrimary:
        type: string
        description: 'Identifies Primary Channel. '
      division:
        type: string
        description: ''
      subDivision:
        type: string
    required:
      - id
      - isPrimary
  Agencies:
    type: object
    title: Agencies
    x-examples:
      agency:
        id: 5dee39514d9c000a905b421e
        name: Ally Bank
        commission: 15
        roles:
          - Buying
          - Paying
          - Billing
        contact: 5e84eadd4d9c0030cf34641e
        address: '1111 St Gregory Street,UNITED STATES,OH,Cincinnati,45202'
        startDate: '2020-04-15'
        endDate: '2020-05-31'
    description: Data object the contains Agency attributes
    properties:
      address:
        type: string
        description: Address of the agency contact
      commission:
        type: string
        description: Not required. If empty will default from the MDM Agency
      contactId:
        type: string
        description: AOS ID of the Contact person - UM
      startDate:
        type: string
        format: date
      id:
        type: string
        description: AOS ID for the Agency MDM
      roles:
        type: array
        description: Not required. If empty default to Buying
        items:
          type: string
      endDate:
        type: string
    required:
      - id
  PlanDTO:
    type: object
    title: PlanDTO
    description: Data obect that contains Plan header attributes.
    x-tags:
      - plan-header-external-controller
    x-examples:
      example-1: {}
    properties:
      AccountExecutives:
        type: array
        description: Sales people that are managing the Plan. One AE is required and will be set as Primary
        items:
          $ref: '#/definitions/AccountExecutives'
      Advertisers:
        $ref: '#/definitions/Advertisers'
      Agencies:
        type: array
        description: Data object the contains Agency attributes
        items:
          $ref: '#/definitions/Agencies'
      calendarId:
        type: string
        description: AOS ID of the Calendar
      Channels:
        type: array
        description: Data object the contains Channel attributes
        items:
          $ref: '#/definitions/Channels'
      dealYearId:
        type: string
        description: AOS ID of a deal year.
      Demos:
        type: array
        description: Data object the contains Demo attributes
        items:
          $ref: '#/definitions/Demos'
      dueDate:
        type: string
        example: 'yyyy-MM-dd,hh:mm a'
        description: Date and Time
      endDate:
        type: string
        example: yyyy-MM-dd
        description: End date of the Plan flight
      endPeriodId:
        type: string
        description: AOS ID from the Calendar period in MRD. If empty default to the period for the flight end date
      equivalized:
        type: boolean
        description: Not required.If empty default to false
      fluidity:
        type: boolean
        description: Not required. If empty default to false
      guaranteed:
        type: boolean
        description: Not required. If empty default to false
      Hiatus:
        type: array
        description: Data object the contains dates and/or date ranges of the hiatus dates
        items:
          $ref: '#/definitions/Hiatus'
      marketPlaceId:
        type: string
        description: AOS Identifier for the Marketplace MRD
        example: 5e2540844d9c00600d5a000a
      orderTypeId:
        type: string
        description: AOS ID of the order type - MRD
      planClassId:
        type: string
        description: AOS ID of the Planclass MRD
      ExternalSourceSystems:
        $ref: '#/definitions/ExternalSourceSystems'
      planName:
        type: string
        description: 'If plan name is empty, default name generated'
      planNotes:
        type: string
        description: Free text that can be printed on the reports
      platform:
        type: string
        description: 'Defines the main platform for the Plan. Choices are LINEAR, DIGItAL or CONVERGED'
        enum:
          - LINEAR
          - DIGITAL
          - CONVERGED
      Ratecards:
        type: array
        description: Data object the contains Ratecard attributes
        items:
          $ref: '#/definitions/RateCards'
      ratingStreamId:
        type: string
        description: AOS ID of the rating stream MRD
      startDate:
        type: string
        example: yyyy-MM-dd
        description: End date of the Plan flight
      startPeriodId:
        type: string
        description: AOS ID from the Calendar period in MRD. If empty default to the period for the flight start date
      versionName:
        type: string
        description: Not required. If empty default to generated version name
      CustomFields:
        $ref: '#/definitions/CustomFields'
    required:
      - platform
  CustomFields:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: CustomFields
paths:
  '/v1/{apiKey}/plan/planHeader':
    post:
      tags:
        - plan-header-external-controller
      summary: Create Plan Header
      description: 'Creates Plan header '
      operationId: createPlanHeaderUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: apiKey
          in: path
          description: apiKey
          required: true
          type: string
        - in: body
          name: planDTO
          description: planDTO
          required: true
          schema:
            $ref: '#/definitions/PlanDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GenericResponse'
      deprecated: false
host: tvs-dev-gw.operativeone.com
info:
  description: 'API to Create new Plan <br> versionHistory <br> -------------- <br> 20202-Apr-11 Marina Yurovsky - Version - 1.0.0. - Initial version.'
  version: '1.0'
  title: Plan Header External API Post
  contact:
    name: API team
    email: apiteam@operative.com
  license:
    name: Copyright 2020 Operative
  termsOfService: 'http://www.operative.com'
swagger: '2.0'
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: plan-header-external-controller
    description: Plan Header External Controller
